version: '3.8'

services:
  dashboard:
    image: velesstan/dashboard
    ports:
      - 8080:80
  core:
    image: velesstan/core
    restart: always
    ports:
      - 3000:3000
    env_file: app.env
    depends_on:
      - database
  database:
    image: mongo:4.2.10
    restart: always
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongodb:/data/db
    command: mongod --config /etc/mongod.conf
    env_file: app.env
    ports:
      - '27017:27017'
